CC := gcc
CFLAGS := -c -Wall -Werror
LDFLAGS := 

SIG_HANDLER_SOURCES := signal_handler.c
SIG_HANDLER_EXECUTABLE := signal_handler
SIG_ALARM_SOURCES := signal_alarm.c
SIG_ALARM_EXECUTABLE := signal_alarm
SIG_SEGFAULT_SOURCES := signal_segfault.c
SIG_SEGFAULT_EXECUTABLE := signal_segfault
SIG_SIGACTION_SOURCES := signal_sigaction.c
SIG_SIGACTION_EXECUTABLE := signal_sigaction

SIG_HANDLER_OBJECTS := $(SIG_HANDLER_SOURCES:.c=.o)
SIG_ALARM_OBJECTS := $(SIG_ALARM_SOURCES:.c=.o)
SIG_SEGFAULT_OBJECTS := $(SIG_SEGFAULT_SOURCES:.c=.o)
SIG_SIGACTION_OBJECTS := $(SIG_SIGACTION_SOURCES:.c=.o)

all: $(SIG_HANDLER_EXECUTABLE) $(SIG_ALARM_EXECUTABLE) $(SIG_SEGFAULT_EXECUTABLE) $(SIG_SIGACTION_EXECUTABLE)

debug: CFLAGS += -g
debug: $(SIG_HANDLER_EXECUTABLE) $(SIG_ALARM_EXECUTABLE) $(SIG_SEGFAULT_EXECUTABLE) $(SIG_SIGACTION_EXECUTABLE)

clean:
	rm -rf $(SIG_HANDLER_OBJECTS) $(SIG_ALARM_OBJECTS) $(SIG_SEGFAULT_OBJECTS) $(SIG_SIGACTION_OBJECTS)
	rm -rf $(SIG_HANDLER_EXECUTABLE) $(SIG_ALARM_EXECUTABLE) $(SIG_SEGFAULT_EXECUTABLE) $(SIG_SIGACTION_EXECUTABLE)
	rm -rf *.d

# pull in dependency info for *existing* .o files
-include $(OBJECTS:.o=.d)

$(SIG_HANDLER_EXECUTABLE): $(SIG_HANDLER_OBJECTS)
	$(CC) $(LDFLAGS) $(SIG_HANDLER_OBJECTS) -o $@

$(SIG_ALARM_EXECUTABLE): $(SIG_ALARM_OBJECTS)
	$(CC) $(LDFLAGS) $(SIG_ALARM_OBJECTS) -o $@

$(SIG_SEGFAULT_EXECUTABLE): $(SIG_SEGFAULT_OBJECTS)
	$(CC) $(LDFLAGS) $(SIG_SEGFAULT_OBJECTS) -o $@

$(SIG_SIGACTION_EXECUTABLE): $(SIG_SIGACTION_OBJECTS)
	$(CC) $(LDFLAGS) $(SIG_SIGACTION_OBJECTS) -o $@

%.o : %.c
	$(CC) $(CFLAGS) $< -o $@
	$(CC) -MM $< > $*.d
